const descuentos = [{
  id: 1,
  img: 'http://salvacash.com.ar/wp-content/uploads/2023/06/carrefourVisa.png',
  titulo: "Los miércoles al 20%",  
  categoria: "Supermercados",
  tipoBeneficio: "Descuento",
  porcentajeDescuento: 20,
  diasVigencia: "Miércoles",
  facilitador: "Tarjeta de crédito",
  medioPago1: "Visa",
  medioPago2: "",
  emisor: "Macro",
  formaPago: "Offline",
  generador: "Carrefour",
  momentoBeneficio: "Fin de mes",
  topeReintegro: "2000 mensuales",
},
{
  id: 2,
  img: 'https://salvacash.com.ar/wp-content/uploads/2023/06/changomasSupervielle.png',
  titulo: "Finde de Modo",
  categoria: "Supermercados",
  tipoBeneficio: "Descuento",
  porcentajeDescuento: 15,
  diasVigencia: "Sábado",
  facilitador: "Billetera electronica",
  medioPago1: "Modo",
  medioPago2: "Visa",
  emisor: "Supervielle",
  formaPago: "Online",
  generador: "Jumbo",
  momentoBeneficio: "Al consumo",
  topeReintegro: "",
},
{
  id: 3,
  img: 'http://salvacash.com.ar/wp-content/uploads/2023/06/cotoComunidad.png',
  titulo: "Coto te conoce",
  categoria: "Supermercados",
  tipoBeneficio: "Descuento",
  porcentajeDescuento: 15,
  diasVigencia: "Martes",
  facilitador: "Membresía",
  medioPago1: "Efectivo",
  medioPago2: "",
  emisor: "Coto",
  formaPago: "Offline",
  generador: "Coto",
  momentoBeneficio: "Al consumo",
  topeReintegro: "5000 mensuales",
},
{
  id: 4,
  img: 'http://salvacash.com.ar/wp-content/uploads/2023/06/cotoHsbc.png',
  titulo: "Tu mejor plan para el viernes",
  categoria: "Supermercados",
  tipoBeneficio: "Descuento",
  porcentajeDescuento: 20,
  diasVigencia: "Viernes",
  facilitador: "Tarjeta de crébito",
  medioPago1: "Mastercard",
  medioPago2: "",
  emisor: "HSBC",
  formaPago: "Online",
  generador: "Coto",
  momentoBeneficio: "Fin de mes",
  topeReintegro: "",
},
{
  id: 5,
  img: 'http://salvacash.com.ar/wp-content/uploads/2023/06/jumboSupervielle.png',
  titulo: "Sin Supervielle no existís",
  categoria: "Supermercados",
  tipoBeneficio: "Descuento",
  porcentajeDescuento: 20,
  diasVigencia: "Martes",
  facilitador: "Tarjeta de débito",
  medioPago1: "Maestro",
  medioPago2: "",
  emisor: "Supervielle",
  formaDePago: "Offline",
  generador: "Chango Más",
  momentoBeneficio: "Fin de mes",
  topeReintegro: "",
},
]
